version: '3.8'
services:
  develop:
    command: yarn dev
    build:
      target: frontend
      context: .
      dockerfile: ./Dockerfile
    container_name: frontend_dev
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  build:
    command: yarn build
    build:
      target: frontend
      context: .
      dockerfile: ./Dockerfile
    container_name: frontend_build
    volumes:
      - .:/app
      - node_modules:/app/node_modules

  # Nginx
  webserver:
    depends_on:
      - build
    build:
      context: .
      dockerfile: ./Dockerfile
      target: nginx
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./dist:/usr/share/nginx/html  

volumes:
  node_modules:
