version: '3.8'
services:
  develop:
    command: yarn serve
    build:
      target: develop
      context: .
      dockerfile: ./Dockerfile
    container_name: develop
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  build:
    build:
      target: production
      context: .
      dockerfile: ./Dockerfile
    container_name: build
    volumes:
      - .:/app

volumes:
  node_modules:
