version: '3.8'
services:
  frontend:
    command: yarn serve
    build:
      target: frontend
      context: .
      dockerfile: ./Dockerfile
    container_name: frontend_dev
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  # Nginx
  webserver:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: webserver
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./dist:/usr/share/nginx/html  

volumes:
  node_modules:
